// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Valve.VR
{
    using System;
    using UnityEngine;
    
    
    public class SteamVR_Input_ActionSet_default_In : Valve.VR.SteamVR_Action_List
    {
        
        public Valve.VR.SteamVR_Action_Boolean InteractUI;
        
        public Valve.VR.SteamVR_Action_Boolean Teleport;
        
        public Valve.VR.SteamVR_Action_Boolean GrabPinch;
        
        public Valve.VR.SteamVR_Action_Boolean GrabGrip;
        
        public Valve.VR.SteamVR_Action_Pose Pose;
        
        public Valve.VR.SteamVR_Action_Skeleton SkeletonLeftHand;
        
        public Valve.VR.SteamVR_Action_Skeleton SkeletonRightHand;
        
        public Valve.VR.SteamVR_Action_Single Squeeze;
    }
}
